// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4edOEg4TeyFXvjcwGStcYcHYZrTuVyTA',
    appId: '1:752144910838:web:cdfa1a0f912c91a5f55fd7',
    messagingSenderId: '752144910838',
    projectId: 'aadocaopets',
    authDomain: 'aadocaopets.firebaseapp.com',
    storageBucket: 'aadocaopets.firebasestorage.app',
    measurementId: 'G-VGW8D7YE3T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCu-DjNT7luQLPY_1ELSkVxad7BT_qNg8',
    appId: '1:752144910838:android:b32a5dbc5641822df55fd7',
    messagingSenderId: '752144910838',
    projectId: 'aadocaopets',
    storageBucket: 'aadocaopets.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4edOEg4TeyFXvjcwGStcYcHYZrTuVyTA',
    appId: '1:752144910838:web:7d78ab76a74043e7f55fd7',
    messagingSenderId: '752144910838',
    projectId: 'aadocaopets',
    authDomain: 'aadocaopets.firebaseapp.com',
    storageBucket: 'aadocaopets.firebasestorage.app',
    measurementId: 'G-DMF9GLPWRD',
  );

}